{
 "title": "Go Metrics",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "请求", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MAX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.00,sum(rate(idefav_httpserver_request_duration_seconds_bucket{}[1h]))by (le,Path))",
     "legendFormat": "{{Path}}"
    }
   ]
  },
  {
   "title": "99线",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(idefav_httpserver_request_duration_seconds_bucket{}[1h]))by (le,Path))",
     "legendFormat": "{{Path}}"
    }
   ]
  },
  {
   "title": "90线",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(idefav_httpserver_request_duration_seconds_bucket{}[1h]))by (le,Path))",
     "legendFormat": "{{Path}}"
    }
   ]
  },
  {
   "title": "95线",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(idefav_httpserver_request_duration_seconds_bucket{}[1h]))by (le,Path))",
     "legendFormat": "{{Path}}"
    }
   ]
  },
  {
   "title": "75线",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75,sum(rate(idefav_httpserver_request_duration_seconds_bucket{}[1h]))by (le,Path))",
     "legendFormat": "{{Path}}"
    }
   ]
  },
  {
   "title": "50线",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,sum(rate(idefav_httpserver_request_duration_seconds_bucket{}[1h]))by (le,Path))",
     "legendFormat": "{{Path}}"
    }
   ]
  },
  {
   "title": "25线",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25,sum(rate(idefav_httpserver_request_duration_seconds_bucket{}[1h]))by (le,Path))",
     "legendFormat": "{{Path}}"
    }
   ]
  },
  {
   "title": "MIN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.0,sum(rate(idefav_httpserver_request_duration_seconds_bucket{}[1h]))by (le,Path))",
     "legendFormat": "{{Path}}"
    }
   ]
  }
 ]
}